### ISSUE TITLE
Packaging for Conda recipe

### ISSUE THREAD

**Issue by apcamargo** [refresh-bio/vclust#15]
It would be great to have vClust as a package in Bioconda to make installation easier. Ideally the recipe would be built from a PyPI release, which requires a proper packaging.

Not sure what are the plans at the moment, but I wanted to create this issue to check if there's interest in that. Apparently some binary dependencies are not yet in Bioconda (e.g. LZ-ANI and multi-fasta-split), so some work would have to be done in this regard.

Another advantage of having vClust in a proper package is being able to call it just by `vclust` (instead of pointing to the script path) through [executable scripts](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#creating-executable-scripts).

**Comment by agudys** [comment]
Hello! 

We are planning to upload Vclust to both, PyPI and Bioconda. Hope it is going to be available soon. Will let you know once it is ready.

Best,
Adam

**Comment by agudys** [comment]
Hello @apcamargo,

Vclust is finally available through Bioconda as a self-contained package (with submodules built-in): https://anaconda.org/bioconda/vclust

Best,
Adam

**Comment by apcamargo** [comment]
Thanks, @agudys!

**Comment by aziele** [comment]
Hi @apcamargo! Vclust is now available on PyPI and can be run with just `vclust` instead of pointing to the script path. Thanks!
