### ISSUE TITLE
Min. query coverage of vclust cluster when classifying viruses into species following ICTV standards

### ISSUE THREAD

**Issue by lingyi-owl** [refresh-bio/vclust#17]
Hi,
I use vclust script to classify viruses into species and genera following ICTV standards.

The script of assigning viruses into putative species (tANI ≥ 95%) is:
`vclust cluster -i ani.tsv -o species.tsv --ids ani.ids.tsv --algorithm complete --metric tani --tani 0.95`

What is the minimum query coverage used in this script?

Thanks in advance,
Lingyi

**Comment by aziele** [comment]
Hi,

The tANI measure is equivalent to the intergenomic similarity used by [VIRIDIC](https://doi.org/10.3390/v12111268). Unlike ANI, which is calculated in respect to the alignment length, tANI takes into account the full lengths of the genomes being compared. This means that tANI reflects the nucleotide identity between two genome sequences, assuming both genomes have 100% coverage. Therefore, it is only appropriate to use tANI when working with complete genomes.

The formula for tANI is as follows:

tANI = (idAB + idBA) / (lenA + lenB) × 100

where:

- idAB - identicial nucleotides when genome A is aligned to genome B
- idBA - identicial nucleotides when genome B is aligned to genome A
- lenA - length of genome A
- lenB - length of genome B

When clustering with `--tani 0.95`, Vclust will make connections between genomes that have a tANI value ≥ 95%.

Best,
Andrzej
